ct_management_account_id    = "trustsoft-aft-master"
log_archive_account_id      = "Log Archive"
audit_account_id            = "Audit"
aft_management_account_id   = "trustsoft-aft-controller"
github_username             = "trustsoft-eu"
ct_home_region              = "eu-central-1"
tf_backend_secondary_region = "eu-west-1"
aws_profile                 = "trustsoft-aft-master"
